// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.Student.Repositories;

#nullable disable

namespace PRN232.Student.Repositories.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260716160116_InitialStudent")]
    partial class InitialStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.Student.Repositories.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student01@lms.local",
                            FullName = "Nguyen An 01"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student02@lms.local",
                            FullName = "Tran Binh 02"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student03@lms.local",
                            FullName = "Le Chi 03"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(2004, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student04@lms.local",
                            FullName = "Pham Dung 04"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student05@lms.local",
                            FullName = "Hoang Hanh 05"
                        },
                        new
                        {
                            StudentId = 6,
                            DateOfBirth = new DateTime(2001, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student06@lms.local",
                            FullName = "Phan Khoa 06"
                        },
                        new
                        {
                            StudentId = 7,
                            DateOfBirth = new DateTime(2002, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student07@lms.local",
                            FullName = "Vu Linh 07"
                        },
                        new
                        {
                            StudentId = 8,
                            DateOfBirth = new DateTime(2003, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student08@lms.local",
                            FullName = "Dang Minh 08"
                        },
                        new
                        {
                            StudentId = 9,
                            DateOfBirth = new DateTime(2004, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student09@lms.local",
                            FullName = "Bui Nam 09"
                        },
                        new
                        {
                            StudentId = 10,
                            DateOfBirth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student10@lms.local",
                            FullName = "Do Quyen 10"
                        },
                        new
                        {
                            StudentId = 11,
                            DateOfBirth = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student11@lms.local",
                            FullName = "Nguyen An 11"
                        },
                        new
                        {
                            StudentId = 12,
                            DateOfBirth = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student12@lms.local",
                            FullName = "Tran Binh 12"
                        },
                        new
                        {
                            StudentId = 13,
                            DateOfBirth = new DateTime(2003, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student13@lms.local",
                            FullName = "Le Chi 13"
                        },
                        new
                        {
                            StudentId = 14,
                            DateOfBirth = new DateTime(2004, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student14@lms.local",
                            FullName = "Pham Dung 14"
                        },
                        new
                        {
                            StudentId = 15,
                            DateOfBirth = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student15@lms.local",
                            FullName = "Hoang Hanh 15"
                        },
                        new
                        {
                            StudentId = 16,
                            DateOfBirth = new DateTime(2001, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student16@lms.local",
                            FullName = "Phan Khoa 16"
                        },
                        new
                        {
                            StudentId = 17,
                            DateOfBirth = new DateTime(2002, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student17@lms.local",
                            FullName = "Vu Linh 17"
                        },
                        new
                        {
                            StudentId = 18,
                            DateOfBirth = new DateTime(2003, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student18@lms.local",
                            FullName = "Dang Minh 18"
                        },
                        new
                        {
                            StudentId = 19,
                            DateOfBirth = new DateTime(2004, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student19@lms.local",
                            FullName = "Bui Nam 19"
                        },
                        new
                        {
                            StudentId = 20,
                            DateOfBirth = new DateTime(2000, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student20@lms.local",
                            FullName = "Do Quyen 20"
                        },
                        new
                        {
                            StudentId = 21,
                            DateOfBirth = new DateTime(2001, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student21@lms.local",
                            FullName = "Nguyen An 21"
                        },
                        new
                        {
                            StudentId = 22,
                            DateOfBirth = new DateTime(2002, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student22@lms.local",
                            FullName = "Tran Binh 22"
                        },
                        new
                        {
                            StudentId = 23,
                            DateOfBirth = new DateTime(2003, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student23@lms.local",
                            FullName = "Le Chi 23"
                        },
                        new
                        {
                            StudentId = 24,
                            DateOfBirth = new DateTime(2004, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student24@lms.local",
                            FullName = "Pham Dung 24"
                        },
                        new
                        {
                            StudentId = 25,
                            DateOfBirth = new DateTime(2000, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student25@lms.local",
                            FullName = "Hoang Hanh 25"
                        },
                        new
                        {
                            StudentId = 26,
                            DateOfBirth = new DateTime(2001, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student26@lms.local",
                            FullName = "Phan Khoa 26"
                        },
                        new
                        {
                            StudentId = 27,
                            DateOfBirth = new DateTime(2002, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student27@lms.local",
                            FullName = "Vu Linh 27"
                        },
                        new
                        {
                            StudentId = 28,
                            DateOfBirth = new DateTime(2003, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student28@lms.local",
                            FullName = "Dang Minh 28"
                        },
                        new
                        {
                            StudentId = 29,
                            DateOfBirth = new DateTime(2004, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student29@lms.local",
                            FullName = "Bui Nam 29"
                        },
                        new
                        {
                            StudentId = 30,
                            DateOfBirth = new DateTime(2000, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student30@lms.local",
                            FullName = "Do Quyen 30"
                        },
                        new
                        {
                            StudentId = 31,
                            DateOfBirth = new DateTime(2001, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student31@lms.local",
                            FullName = "Nguyen An 31"
                        },
                        new
                        {
                            StudentId = 32,
                            DateOfBirth = new DateTime(2002, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student32@lms.local",
                            FullName = "Tran Binh 32"
                        },
                        new
                        {
                            StudentId = 33,
                            DateOfBirth = new DateTime(2003, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student33@lms.local",
                            FullName = "Le Chi 33"
                        },
                        new
                        {
                            StudentId = 34,
                            DateOfBirth = new DateTime(2004, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student34@lms.local",
                            FullName = "Pham Dung 34"
                        },
                        new
                        {
                            StudentId = 35,
                            DateOfBirth = new DateTime(2000, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student35@lms.local",
                            FullName = "Hoang Hanh 35"
                        },
                        new
                        {
                            StudentId = 36,
                            DateOfBirth = new DateTime(2001, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student36@lms.local",
                            FullName = "Phan Khoa 36"
                        },
                        new
                        {
                            StudentId = 37,
                            DateOfBirth = new DateTime(2002, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student37@lms.local",
                            FullName = "Vu Linh 37"
                        },
                        new
                        {
                            StudentId = 38,
                            DateOfBirth = new DateTime(2003, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student38@lms.local",
                            FullName = "Dang Minh 38"
                        },
                        new
                        {
                            StudentId = 39,
                            DateOfBirth = new DateTime(2004, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student39@lms.local",
                            FullName = "Bui Nam 39"
                        },
                        new
                        {
                            StudentId = 40,
                            DateOfBirth = new DateTime(2000, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student40@lms.local",
                            FullName = "Do Quyen 40"
                        },
                        new
                        {
                            StudentId = 41,
                            DateOfBirth = new DateTime(2001, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student41@lms.local",
                            FullName = "Nguyen An 41"
                        },
                        new
                        {
                            StudentId = 42,
                            DateOfBirth = new DateTime(2002, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student42@lms.local",
                            FullName = "Tran Binh 42"
                        },
                        new
                        {
                            StudentId = 43,
                            DateOfBirth = new DateTime(2003, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student43@lms.local",
                            FullName = "Le Chi 43"
                        },
                        new
                        {
                            StudentId = 44,
                            DateOfBirth = new DateTime(2004, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student44@lms.local",
                            FullName = "Pham Dung 44"
                        },
                        new
                        {
                            StudentId = 45,
                            DateOfBirth = new DateTime(2000, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student45@lms.local",
                            FullName = "Hoang Hanh 45"
                        },
                        new
                        {
                            StudentId = 46,
                            DateOfBirth = new DateTime(2001, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student46@lms.local",
                            FullName = "Phan Khoa 46"
                        },
                        new
                        {
                            StudentId = 47,
                            DateOfBirth = new DateTime(2002, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student47@lms.local",
                            FullName = "Vu Linh 47"
                        },
                        new
                        {
                            StudentId = 48,
                            DateOfBirth = new DateTime(2003, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student48@lms.local",
                            FullName = "Dang Minh 48"
                        },
                        new
                        {
                            StudentId = 49,
                            DateOfBirth = new DateTime(2004, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student49@lms.local",
                            FullName = "Bui Nam 49"
                        },
                        new
                        {
                            StudentId = 50,
                            DateOfBirth = new DateTime(2000, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student50@lms.local",
                            FullName = "Do Quyen 50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
