using Microsoft.EntityFrameworkCore;
using PRN232.Course.Repositories;
using PRN232.LMS.Contracts;
using CourseEntity = PRN232.Course.Repositories.Course;

namespace PRN232.Course.Services;

public sealed class CourseLmsService(IUnitOfWork uow, StudentLookup.StudentLookupClient studentClient) : ICourseLmsService
{
    public async Task<PagedResult> GetSemestersAsync(CollectionQueryParameters p, CancellationToken ct = default)
    {
        var q = uow.Semesters.Query().AsNoTracking().Include(x => x.Courses).AsQueryable(); if (!string.IsNullOrWhiteSpace(p.Search)) { var s = p.Search.ToLower(); q = q.Where(x => x.SemesterName.ToLower().Contains(s)); }
        return await PageAsync(q, p, x => Select(Map(x, HasExpand(p.Expand, "courses")), p.Fields), ct);
    }
    public async Task<SemesterResponse> GetSemesterAsync(int id, string? expand, CancellationToken ct = default) { var value = await uow.Semesters.Query().AsNoTracking().Include(x => x.Courses).SingleOrDefaultAsync(x => x.SemesterId == id, ct) ?? throw Missing("Semester", id); return Map(value, HasExpand(expand, "courses")); }
    public async Task<SemesterResponse> SaveSemesterAsync(int? id, SemesterRequest r, CancellationToken ct = default) { var value = id is null ? new Semester() : await uow.Semesters.GetByIdAsync(id.Value, ct) ?? throw Missing("Semester", id.Value); value.SemesterName = r.SemesterName.Trim(); value.StartDate = r.StartDate; value.EndDate = r.EndDate; if (id is null) await uow.Semesters.AddAsync(value, ct); else uow.Semesters.Update(value); await uow.SaveChangesAsync(ct); return Map(value, false); }
    public async Task DeleteSemesterAsync(int id, CancellationToken ct = default) { var value = await uow.Semesters.GetByIdAsync(id, ct) ?? throw Missing("Semester", id); uow.Semesters.Remove(value); await uow.SaveChangesAsync(ct); }
    public async Task<PagedResult> GetSubjectsAsync(CollectionQueryParameters p, CancellationToken ct = default) { var q = uow.Subjects.Query().AsNoTracking().Include(x => x.Courses).AsQueryable(); if (!string.IsNullOrWhiteSpace(p.Search)) { var s = p.Search.ToLower(); q = q.Where(x => x.SubjectName.ToLower().Contains(s) || x.SubjectCode.ToLower().Contains(s)); } return await PageAsync(q, p, x => Select(Map(x, HasExpand(p.Expand, "courses")), p.Fields), ct); }
    public async Task<SubjectResponse> GetSubjectAsync(int id, string? expand, CancellationToken ct = default) { var value = await uow.Subjects.Query().AsNoTracking().Include(x => x.Courses).SingleOrDefaultAsync(x => x.SubjectId == id, ct) ?? throw Missing("Subject", id); return Map(value, HasExpand(expand, "courses")); }
    public async Task<SubjectResponse> SaveSubjectAsync(int? id, SubjectRequest r, CancellationToken ct = default) { if (await uow.Subjects.Query().AnyAsync(x => x.SubjectId != id && x.SubjectCode == r.SubjectCode.Trim(), ct)) throw new BadRequestException("Subject code is already in use."); var value = id is null ? new Subject() : await uow.Subjects.GetByIdAsync(id.Value, ct) ?? throw Missing("Subject", id.Value); value.SubjectCode = r.SubjectCode.Trim().ToUpperInvariant(); value.SubjectName = r.SubjectName.Trim(); value.Credit = r.Credit; if (id is null) await uow.Subjects.AddAsync(value, ct); else uow.Subjects.Update(value); await uow.SaveChangesAsync(ct); return Map(value, false); }
    public async Task DeleteSubjectAsync(int id, CancellationToken ct = default) { var value = await uow.Subjects.GetByIdAsync(id, ct) ?? throw Missing("Subject", id); uow.Subjects.Remove(value); await uow.SaveChangesAsync(ct); }
    public async Task<PagedResult> GetCoursesAsync(CollectionQueryParameters p, CancellationToken ct = default) { var q = uow.Courses.Query().AsNoTracking().Include(x => x.Semester).Include(x => x.Subject).Include(x => x.Enrollments).AsQueryable(); if (!string.IsNullOrWhiteSpace(p.Search)) { var s = p.Search.ToLower(); q = q.Where(x => x.CourseName.ToLower().Contains(s) || x.Subject.SubjectName.ToLower().Contains(s)); } return await PageAsync(q, p, x => Select(Map(x, p.Expand, new Dictionary<int, StudentSummary>()), p.Fields), ct); }
    public async Task<CourseResponse> GetCourseAsync(int id, string? expand, CancellationToken ct = default) { var value = await uow.Courses.Query().AsNoTracking().Include(x => x.Semester).Include(x => x.Subject).Include(x => x.Enrollments).SingleOrDefaultAsync(x => x.CourseId == id, ct) ?? throw Missing("Course", id); var students = await LookupStudentsAsync(value.Enrollments.Select(x => x.StudentId), ct); return Map(value, expand, students); }
    public async Task<CourseResponse> SaveCourseAsync(int? id, CourseRequest r, CancellationToken ct = default) { await EnsureCourseReferencesAsync(r, ct); var value = id is null ? new CourseEntity() : await uow.Courses.GetByIdAsync(id.Value, ct) ?? throw Missing("Course", id.Value); value.CourseName = r.CourseName.Trim(); value.SemesterId = r.SemesterId; value.SubjectId = r.SubjectId; if (id is null) await uow.Courses.AddAsync(value, ct); else uow.Courses.Update(value); await uow.SaveChangesAsync(ct); return await GetCourseAsync(value.CourseId, null, ct); }
    public async Task DeleteCourseAsync(int id, CancellationToken ct = default) { var value = await uow.Courses.GetByIdAsync(id, ct) ?? throw Missing("Course", id); uow.Courses.Remove(value); await uow.SaveChangesAsync(ct); }
    public async Task<PagedResult> GetEnrollmentsAsync(CollectionQueryParameters p, CancellationToken ct = default) { var q = uow.Enrollments.Query().AsNoTracking().Include(x => x.Course).AsQueryable(); if (!string.IsNullOrWhiteSpace(p.Search)) { var s = p.Search.ToLower(); q = q.Where(x => x.Status.ToLower().Contains(s) || x.Course.CourseName.ToLower().Contains(s)); } var list = await q.OrderByDescending(x => x.EnrollDate).ToListAsync(ct); var students = await LookupStudentsAsync(list.Select(x => x.StudentId), ct); return Page(list, p, x => Select(Map(x, p.Expand, students), p.Fields)); }
    public async Task<EnrollmentResponse> GetEnrollmentAsync(int id, string? expand, CancellationToken ct = default) { var value = await uow.Enrollments.Query().AsNoTracking().Include(x => x.Course).SingleOrDefaultAsync(x => x.EnrollmentId == id, ct) ?? throw Missing("Enrollment", id); return Map(value, expand, await LookupStudentsAsync([value.StudentId], ct)); }
    public async Task<EnrollmentResponse> SaveEnrollmentAsync(int? id, EnrollmentRequest r, CancellationToken ct = default) { var student = await studentClient.GetStudentAsync(new StudentIdRequest { StudentId = r.StudentId }, cancellationToken: ct); if (!student.Exists) throw new NotFoundException($"Student with id {r.StudentId} was not found."); if (!await uow.Courses.Query().AnyAsync(x => x.CourseId == r.CourseId, ct)) throw Missing("Course", r.CourseId); var value = id is null ? new Enrollment() : await uow.Enrollments.GetByIdAsync(id.Value, ct) ?? throw Missing("Enrollment", id.Value); value.StudentId = r.StudentId; value.CourseId = r.CourseId; value.EnrollDate = r.EnrollDate; value.Status = r.Status.Trim(); if (id is null) await uow.Enrollments.AddAsync(value, ct); else uow.Enrollments.Update(value); await uow.SaveChangesAsync(ct); return await GetEnrollmentAsync(value.EnrollmentId, "student,course", ct); }
    public async Task DeleteEnrollmentAsync(int id, CancellationToken ct = default) { var value = await uow.Enrollments.GetByIdAsync(id, ct) ?? throw Missing("Enrollment", id); uow.Enrollments.Remove(value); await uow.SaveChangesAsync(ct); }
    public Task<IReadOnlyList<Enrollment>> GetEnrollmentsForStudentsAsync(IReadOnlyCollection<int> ids, CancellationToken ct = default) => uow.Enrollments.Query().AsNoTracking().Include(x => x.Course).Where(x => ids.Contains(x.StudentId)).ToListAsync(ct).ContinueWith(x => (IReadOnlyList<Enrollment>)x.Result, ct);
    public Task<bool> HasEnrollmentsAsync(int studentId, CancellationToken ct = default) => uow.Enrollments.Query().AnyAsync(x => x.StudentId == studentId, ct);
    private async Task EnsureCourseReferencesAsync(CourseRequest r, CancellationToken ct) { if (!await uow.Semesters.Query().AnyAsync(x => x.SemesterId == r.SemesterId, ct)) throw Missing("Semester", r.SemesterId); if (!await uow.Subjects.Query().AnyAsync(x => x.SubjectId == r.SubjectId, ct)) throw Missing("Subject", r.SubjectId); }
    private async Task<Dictionary<int, StudentSummary>> LookupStudentsAsync(IEnumerable<int> ids, CancellationToken ct) { var request = new StudentIdsRequest(); request.StudentIds.AddRange(ids.Distinct()); var reply = await studentClient.GetStudentsAsync(request, cancellationToken: ct); return reply.Students.ToDictionary(x => x.StudentId, x => new StudentSummary { StudentId = x.StudentId, FullName = x.FullName, Email = x.Email }); }
    private static NotFoundException Missing(string type, int id) => new($"{type} with id {id} was not found.");
    private static bool HasExpand(string? value, string name) => value?.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).Contains(name, StringComparer.OrdinalIgnoreCase) == true;
    private static SemesterResponse Map(Semester x, bool courses) => new() { SemesterId = x.SemesterId, SemesterName = x.SemesterName, StartDate = x.StartDate, EndDate = x.EndDate, Courses = courses ? x.Courses.Select(CourseSummaryOf).ToList() : null };
    private static SubjectResponse Map(Subject x, bool courses) => new() { SubjectId = x.SubjectId, SubjectCode = x.SubjectCode, SubjectName = x.SubjectName, Credit = x.Credit, Courses = courses ? x.Courses.Select(CourseSummaryOf).ToList() : null };
    private static CourseResponse Map(CourseEntity x, string? expand, IReadOnlyDictionary<int, StudentSummary> students) => new() { CourseId = x.CourseId, CourseName = x.CourseName, SemesterId = x.SemesterId, SubjectId = x.SubjectId, Semester = HasExpand(expand, "semester") ? new SemesterSummary { SemesterId = x.Semester.SemesterId, SemesterName = x.Semester.SemesterName } : null, Subject = HasExpand(expand, "subject") ? new SubjectSummary { SubjectId = x.Subject.SubjectId, SubjectCode = x.Subject.SubjectCode, SubjectName = x.Subject.SubjectName } : null, Enrollments = HasExpand(expand, "enrollments") ? x.Enrollments.Select(e => Map(e, "student,course", students)).ToList() : null };
    private static EnrollmentResponse Map(Enrollment x, string? expand, IReadOnlyDictionary<int, StudentSummary> students) => new() { EnrollmentId = x.EnrollmentId, StudentId = x.StudentId, CourseId = x.CourseId, EnrollDate = x.EnrollDate, Status = x.Status, Student = HasExpand(expand, "student") && students.TryGetValue(x.StudentId, out var student) ? student : null, Course = HasExpand(expand, "course") ? CourseSummaryOf(x.Course) : null };
    private static CourseSummary CourseSummaryOf(CourseEntity x) => new() { CourseId = x.CourseId, CourseName = x.CourseName };
    private static object Select<T>(T value, string? fields) { if (string.IsNullOrWhiteSpace(fields)) return value!; var names = fields.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).ToHashSet(StringComparer.OrdinalIgnoreCase); return typeof(T).GetProperties().Where(x => names.Contains(x.Name)).ToDictionary(x => char.ToLowerInvariant(x.Name[0]) + x.Name[1..], x => x.GetValue(value)); }
    private static async Task<PagedResult> PageAsync<T>(IQueryable<T> q, CollectionQueryParameters p, Func<T, object> map, CancellationToken ct) { var total = await q.CountAsync(ct); var items = await q.Skip((Math.Max(1, p.Page) - 1) * Math.Clamp(p.Size, 1, 100)).Take(Math.Clamp(p.Size, 1, 100)).ToListAsync(ct); return Page(items, p, map, total); }
    private static PagedResult Page<T>(IReadOnlyList<T> values, CollectionQueryParameters p, Func<T, object> map, int? totalOverride = null) { var page = Math.Max(1, p.Page); var size = Math.Clamp(p.Size, 1, 100); var total = totalOverride ?? values.Count; var take = totalOverride is null ? values.Skip((page - 1) * size).Take(size) : values; return new PagedResult { Items = take.Select(map).ToList(), Pagination = new PaginationMetadata { Page = page, PageSize = size, TotalItems = total, TotalPages = (int)Math.Ceiling(total / (double)size) } }; }
}
